### ISSUE TITLE
Objects get separated

### ISSUE THREAD

**Issue by dehill89** [JMicroVision/jmicrovision#10]
Hello,
I'm using JMicroVision to quantify air voids in asphalt. Right now I have the problem, that the object separation algorithm is cutting objects into parts and I can't figure out why. The spatial calibration is correct and for the maximum shape size I used the maximum provided (58 x 75 mm). The attached image shows an example of such an object. The inserted red line is 4.9 mm long. So the object doesn't exceed the maximum size. Do you have an idea, why this is happening? It won't be a problem for profiles or air void content, but I want to examine the void sizes. I did not have this issue before.
Kind regards
Tobias Di Turi
<img width="1433" alt="Bildschirmfoto 2021-05-26 um 12 13 16" src="https://user-images.githubusercontent.com/74291209/119643873-9306f300-be1c-11eb-8176-c35bfb7abb74.png">

**Comment by nroduit** [comment]
If I remember correctly, the separation algorithm is rather made to separate compact objects (grain). The size is not the only criterion. 
The scope of the algorithm is therefore limited.

**Comment by dehill89** [comment]
Thank you for your answer. I will use the color intensity threshold algorithm.
