### ISSUE TITLE
v1.3.2 Saved project cannot be re-opened. 

### ISSUE THREAD

**Issue by fionachong104** [JMicroVision/jmicrovision#3]
After processing the image, we saved the project from File > Save Project as... in the .jmv format. This .jmv file cannot be reopened and the error messages received are below:

Image Path errors: Unable to find or read vortex; Unable to find or read Copy; Unable to find or read of; Unable to find or read swim; Unable to find or read Ocean

Load Project error: Unable to load the project properly

**Comment by nroduit** [comment]
Could you attach a sample of .jmv file.

**Comment by fionachong104** [comment]
Hi

Here is an example.

Best wishes,

Fiona

**Comment by nroduit** [comment]
It is only possible to attach some file types. Could you send it by email (from my profile). Thanks

**Comment by nroduit** [comment]
I confirm that it is a bug. To reopen your file see https://github.com/JMicroVision/jmicrovision/issues/4#issuecomment-568162946
