### ISSUE TITLE
Cannot reopen counting without grid

### ISSUE THREAD

**Issue by nroduit** [JMicroVision/jmicrovision#4]
v1.3.2
- In point counting select No Grid
- Save project
- Reopen

**Comment by nroduit** [comment]
It will be fixed in 1.3.3 but meanwhile, you can replace [jmicrovision.jar ](https://github.com/JMicroVision/jmicrovision/releases/download/v1.3.2/jmicrovision.jar)located in the install folder. On Windows: C:\Program Files\JMicroVision\app

**Comment by fionachong104** [comment]
Replaced jmicrovision.jar but the problem persisted. When will 1.3.3 be released? Would .jmv files/projects created in 1.3.2 be editable in 1.3.3? 

Thanks

Edit: .jmv files can be reopened through the drop down menu File > Open Project within JMicroVision 1.3.2... They can't be directly 'reopened' from the file directory outside of the programme.

**Comment by nroduit** [comment]
I don't have a release date yet but I test again by replacing the file it works in any situation.
