### ISSUE TITLE
Point counting area limitation: rectangle always has top left corner at top left of image?

### ISSUE THREAD

**Issue by matt-spencer** [JMicroVision/jmicrovision#5]
I'm using JMicroVision 1.3.2 on 64-bit Windows 10 (with the most recent version of jmicrovision.jar). If I use the area editor to create a rectangle whose top left corner is not at the top left of the image, and then use a random grid, the points are always drawn from a rectange of the same size, but with its top left corner at the top left of the image. See attached images of the rectangle in the area editor, and where the points fall. I'm not sure that other kinds of area (circles, polygons) are located correctly either in point counting, but it's harder to work out exactly what happens.

![rectangle](https://user-images.githubusercontent.com/10521944/71666133-91d0b400-2d57-11ea-9a4e-7b23ddbd694e.PNG)
![rectangle2](https://user-images.githubusercontent.com/10521944/71666134-91d0b400-2d57-11ea-81ea-1fdd63f6ebd4.PNG)

**Comment by nroduit** [comment]
I confirmed the issue, the location of the area is wrong. It has been fixed in the next release.
