### ISSUE TITLE
Not able to load a seved project

### ISSUE THREAD

**Issue by taxopoul** [JMicroVision/jmicrovision#6]
1)When I load a photo it asks me to convert it. When I click on "yes" and save the new file, I can't open it again afterwards because "it is not suuperoted". 

![image](https://user-images.githubusercontent.com/61841855/76075548-82f7bf00-5f9d-11ea-8b87-3d6b26b35dc2.png)

![image](https://user-images.githubusercontent.com/61841855/76075560-89863680-5f9d-11ea-860f-0d7d0f4d10a9.png)

![image](https://user-images.githubusercontent.com/61841855/76075625-9f93f700-5f9d-11ea-8a0a-5cd1c392a44d.png)

I guess that if I process the image without converting, then problem 2 arises. 

2)When I save my measurements (like point counting, grain size distribution) to a new project and then open the program to load the project, it doesn't open and a red exclamation mark with the phrase " Unable to load the project properly" appears on the screen

 - OS: Windows 10 64-bit
 - JMicroVision Version 1.3.3

![image](https://user-images.githubusercontent.com/61841855/76075384-3a400600-5f9d-11ea-8566-23050cb7f695.png)

![image](https://user-images.githubusercontent.com/61841855/76075401-45933180-5f9d-11ea-9dca-96d2902c5c2a.png)

![image](https://user-images.githubusercontent.com/61841855/76075362-2c8a8080-5f9d-11ea-9b01-5fd683f2aab2.png)

**Comment by nroduit** [comment]
1) It seems that you convert a tiff file into a tiff file with the same. The conversion cannot be done if the source and the destination have the same name. This will corrupt your original images.

2) Is it files from the same version? Please provide the jmv file or logs from ${user.home}./jmicrovision/jmvision-0.log.0
