### ISSUE TITLE
Help in saving data and exporting them to excel

### ISSUE THREAD

**Issue by taxopoul** [JMicroVision/jmicrovision#7]
Hello,

I have some problems when saving the measurements from the program. I want to load them to excel spreadsheet but some measurements of lenfth or azimuth I end up having instead or this: 123,4567 I have this when I open the excel : 1.234.567.890. You can check my screenshots. 

Any suggestions? I am thinking that I have to set up something on the program, but no idea what. Thanks in advance!

![image](https://user-images.githubusercontent.com/61841855/77175593-2af3a900-6ac3-11ea-8d6a-b3ab154e1fdd.png)

![image](https://user-images.githubusercontent.com/61841855/77175667-46f74a80-6ac3-11ea-922b-97820391a1aa.png)

**Comment by nroduit** [comment]
I would recommend to use [the latest version](https://github.com/JMicroVision/jmicrovision/blob/master/CHANGELOG.md)

I cannot reproduce the issue. It must be clear that the data displayed are rounded values. The question is what are the values in the .csv file with a text editor.

**Comment by taxopoul** [comment]
After a lot of time looking for possible solutions I found out that I had
to switch my PC's region and preferred language in order to recognize the
commas . Problem solved.

Thank you for your time!

**Comment by nroduit** [comment]
It's a really annoying problem with Excel. Using Openoffice you can choose which delimiter character is used.

Alternatively, replace the ";" with "," with a text editor.
