### ISSUE TITLE
Import measurements from other sources and use them in the program

### ISSUE THREAD

**Issue by taxopoul** [JMicroVision/jmicrovision#8]
Hello there, 
this is both a suggestion and a problem that I have. I used ImageJ to do 2D MEasurements and I have the results in excel file but I need to import them in JMicrovision to do some other analysis but I dont know how (or it is not possible). Can you suggest me how to import them to the program? thanks

**Comment by nroduit** [comment]
No, that's not possible because each software has different tools. And the results are not the information needed to recalculate the measurements.
