### ISSUE TITLE
I can't resize areas

### ISSUE THREAD

**Issue by dehill89** [JMicroVision/jmicrovision#9]
I'm trying to make some horizontal profiles of asphalt plane sections. As there are two sections on one image I tried to use profile areas. My problem is now, that I cannot resize the areas. So I have to create a vertical profile area and rotate it 90°, but cannot fit the size afterwards. So I have to trial and error the size of the area before rotating.

Maybe I'm just to dumb to use the function the right way. I can see the tiny points outside the area, but my cursor does not change while hovering over it.

I would be very happy if anybody could help me with that issue.

**Comment by nroduit** [comment]
The rotation tool was added afterwards and does not allow to change the rotation point. However it is possible to readjust the size after rotation.

**Comment by dehill89** [comment]
The resizing is exactly what doesn't work for me. If I hover over the nodes on the corners of the area, the cursor doesn't change. Wherever I click and drag, I just move the entire area.

**Comment by nroduit** [comment]
You should be able to resize with handles (black points):
![Sélection_052](https://user-images.githubusercontent.com/993975/101518209-e629de00-3981-11eb-9382-a38d8a4b8405.png)

**Comment by dehill89** [comment]
Thank you so much, I tried it once again and there is one little point, where the cursor changes and I can resize. I didn't think that they become thicker when zooming in. Maybe it is possible to let the nodes appear in the same size in every zoom state?
